### ISSUE TITLE
wont run on windows 10

### ISSUE THREAD

**Issue by rcmpayne** [Devjam81/idevicerestore-Tools_Windows#1]
C:>idevicerestore.exe /?
This version of C:\idevicerestore.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**Comment by rcmpayne** [comment]
odd now i am getting a error with "The procedure entry point SSL_COMP_free_compression_methods count not be located in the dynamic link library"

**Comment by Devjam81** [comment]
fixed library

**Comment by rcmpayne** [comment]
Does the mega link have the fixes in a new exe?

**Comment by Devjam81** [comment]
here news 
            https://mega.nz/#!ZkVjXQ4D!iiN_nwy5H9q3-WCXD86REUm7UD56Ciq1unRaYoy-fZ0

Date: Wed, 27 Jul 2016 16:21:46 -0700
