### ISSUE TITLE
Method to Completely wipe data without any firmware

### ISSUE THREAD

**Issue by yashsharma45** [Devjam81/idevicerestore-Tools_Windows#11]
Hello

Is there any method or command to completely wipe data and reboot device like factory reset. I have seen some softwares doing that but i am unable to figure out what command it is or what code i have to add into binary file to do that.

Please reply,

Thanks in Advance

**Comment by Devjam81** [comment]
idevicerestore -e



Envoyé depuis mon smartphone Samsung Galaxy.

-------- Message d'origine --------
De : yashsharma45 <notifications@github.com>
Date : 30/06/2018 08:47 (GMT+01:00)
À : Devjam81/Libimobiledevice-idevicerestore-for-Windows <Libimobiledevice-idevicerestore-for-Windows@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Devjam81/Libimobiledevice-idevicerestore-for-Windows] Method to Completely wipe data without any firmware (#11)


Hello

Is there any method or command to completely wipe data and reboot device like factory reset. I have seen some softwares doing that but i am unable to figure out what command it is or what code i have to add into binary file to do that.

Please reply,

Thanks in Advance

**Comment by yashsharma45** [comment]
But I do not want to use any firmware for this. It should work without any firmware but when i try idevicerestore -e. It asks for Firmware. How to do it without any firmware??


Thanks in Advance

**Comment by yashsharma45** [comment]
Hi,

Can you Please tell me whether there is a way to wipe data from device without Restoring it with new firmware? with command -e its downloading new firmware and than wiping data. i don't want new firmware in device.

Thanks
