### ISSUE TITLE
Program occur error that it can't find a procedure's start point of 'ERR_remove_thread_state' 

### ISSUE THREAD

**Issue by misohouse** [Devjam81/idevicerestore-Tools_Windows#2]
![aa](https://cloud.githubusercontent.com/assets/19428462/17129638/3ca64642-534f-11e6-9c92-7c06fbc2c7c5.JPG)

When iPhone's firmware updated 9.3.3, existing idevicerestore.exe couldn't extract firmware from .ipsw file.

So, I downloaded here and tested idevice_id.exe -l

Result is above picture. It looks like libimobliedevice.dll error.

Please fix it. :'-(

**Comment by Devjam81** [comment]
fixed please testing

**Comment by misohouse** [comment]
It works~ thanks!!
