### ISSUE TITLE
idevicerestore.exe doesn't work with a series of iPhone 7

### ISSUE THREAD

**Issue by arosadzinski** [Devjam81/idevicerestore-Tools_Windows#5]
ERROR: Unable to discover device model

**Comment by ghost** [comment]
Yes, same problem for me, unable to restore Iphone 7.
The problem is solved by the latest update of libimobiledevice, can you recompile it for Windows please ?

**Comment by Morphisto** [comment]
I have an IPhone 7 Plus that needs to be restored, and getting the same error. Can someone recompile with the latest update for Windows? Or point me to a tutorial on how to recompile for windows?. I know I need to download/install Ubuntu Desktop.. hmm what else.. Please thanks.

**Comment by arosadzinski** [comment]
Now it is working. Thanks.
