### ISSUE TITLE
(Fix) Can't restore IOS 10.3.2 

### ISSUE THREAD

**Issue by misohouse** [Devjam81/idevicerestore-Tools_Windows#9]
/*NOTE: Updated version data.
Found device in Recovery mode
Identified device as n53ap, iPhone6,2
Latest firmware is iPhone_4.0_64bit_10.3.2_14F89_Restore.ipsw
Verifying 'iPhone_4.0_64bit_10.3.2_14F89_Restore.ipsw'...
Checksum matches.
Extracting BuildManifest from IPSW
Product Version: 10.3.2
Product Build: 14F89 Major: 14
INFO: device serial number is C39M41QGFRC6
Device supports Image4: true
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Found ECID 6654167607760
Getting ApNonce in recovery mode... 15 c4 6b d7 37 dc 0c 3b 9d 30 04 f0 03 51 0a 8e 33 20 43 09
Trying to fetch new SHSH blob
Getting SepNonce in recovery mode... a6 6e cc b9 45 74 8d 70 bc a8 e9 84 07 68 dc 74 31 1e cc ed
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
Extracting filesystem from IPSW
Extracting iBEC.iphone6.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (648344 bytes)...
Recovery Mode Environment:
iBoot build-version=iBoot-3406.60.10
iBoot build-style=RELEASE
Sending AppleLogo...
Extracting applelogo@2x~iphone.s5l8960x.im4p...
Personalizing IMG4 component AppleLogo...
Sending AppleLogo (11640 bytes)...
ramdisk-size=0x10000000
Extracting 058-72508-060.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (41583638 bytes)...
Extracting DeviceTree.n53ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (107919 bytes)...
Extracting kernelcache.release.iphone6...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (12164547 bytes)...
About to restore device...
Waiting for device...
Device 4ccef2ff02874ec1042e32413e8f6e59b8443394 is now connected in restore mode...
Connecting now...
Connected to com.apple.mobile.restored, version 14
Device 4ccef2ff02874ec1042e32413e8f6e59b8443394 has successfully entered restore mode
Hardware Information:
BoardID: 2
ChipID: 35168
UniqueChipID: 6654167607760
ProductionMode: true
Previous restore exit status: 0x100
Starting FDR listener thread
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest Firmware/all_flash/manifest
ERROR: zip_name_locate: Firmware/all_flash/manifest
ERROR: Unable to extract firmware manifest from ipsw
ERROR: Unable to send NOR data
ERROR: Unable to successfully restore device
ERROR: Unable to restore device

Please fix these error.. :(*/

http://idevice.me/download-libimobiledevice-121-updated-ios103/
I download here latest updated version and this is work. thanks.

**Comment by killamoddingteam** [comment]
C:\Users\sabby\Desktop\libi>idevicerestore.exe -u --71F75ED15C64ECDCE7C795BFADCD0576C7BB6247 -c iphone.ipsw
NOTE: using cached version data
Found device in Recovery mode
Identified device as n71map, iPhone8,1
Extracting Restore.plist from IPSW
Product Version: 10.3.2
Product Build: 14F89 Major: 14
INFO: device serial number is DNPR5267GRY7
Device supports Image4: true
Custom firmware requested. Disabled TSS request.
ERROR: zip_name_locate: Firmware/all_flash/all_flash.n71map.production/manifest
ERROR: could not extract Firmware/all_flash/all_flash.n71map.production/manifest from IPSW
